# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    #module = bld.create_ns3_module('multi-link-device', ['core'])
    module = bld.create_ns3_module('multi-link-device', ['wifi'])
    module.source = [
        'model/multi-link-device.cc',
        'helper/multi-link-device-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('multi-link-device')
    module_test.source = [
        'test/multi-link-device-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/multi-link-device-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'multi-link-device'
    headers.source = [
        'model/multi-link-device.h',
        'helper/multi-link-device-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

